import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth/session';
import { db } from '@/lib/db';

export default async function AuditPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser();
  if (!user) redirect('/auth');
  const { id } = await params;
  const audit = await db.audit.findFirst({ where: { id, userId: user.id }, include: { findings: { include: { evidence: { include: { evidence: true } } }, orderBy: [{ priority: 'asc' }, { severity: 'asc' }] }, evidence: true, jobs: { orderBy: { createdAt: 'desc' }, take: 1 } } });
  if (!audit) notFound();
  return <main className="dashboard"><header className="topbar"><Link href="/dashboard" className="brand">PageFix <span>AI</span></Link><Link href="/dashboard">Dashboard</Link></header><div className="container dashboard-main"><div className="label">Audit report</div><h1>{audit.url}</h1><p className="muted">Engine {audit.engineVersion} · {audit.status}</p>{audit.status === 'FAILED' && <div className="error-box">{audit.errorMessage || 'The audit failed. Retry after checking the URL and site accessibility.'}</div>}{audit.status === 'QUEUED' || audit.status === 'RUNNING' ? <div className="card"><h2>Analysis in progress</h2><p className="muted">The job is being processed from browser acquisition through evidence mapping. Refresh this page when it completes.</p></div> : audit.status === 'COMPLETED' ? <><div className="grid grid-3" style={{ marginTop: 24 }}><div className="card"><div className="label">Findings</div><div className="stat">{audit.findings.length}</div></div><div className="card"><div className="label">Evidence items</div><div className="stat">{audit.evidence.length}</div></div><div className="card"><div className="label">Limitations</div><p className="muted">No conversion, revenue, traffic quality, margin, LTV or checkout abandonment can be determined without connected analytics.</p></div></div><section className="card" style={{ marginTop: 24 }}><h2>Prioritized findings</h2>{audit.findings.length === 0 && <p className="muted">No supported purchase-friction finding was detected by the current deterministic engine.</p>}{audit.findings.map(f => <article className="finding" key={f.id}><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><span className="badge">{f.priority}</span><span className={`badge ${f.severity === 'HIGH' ? 'danger' : ''}`}>{f.severity}</span><span className="badge">Confidence {f.confidence}</span></div><h3>{f.title}</h3><p><strong>Observed:</strong> {f.observation}</p><p><strong>Buyer question:</strong> {f.buyerQuestion || 'What would a buyer need to know here?'}</p><p><strong>Why it matters:</strong> {f.whyItMatters}</p><p><strong>Recommended fix:</strong> {f.recommendation}</p><p><strong>Implementation:</strong> {f.implementationSteps}</p><details><summary>Evidence</summary>{f.evidence.map(link => <div key={link.evidenceId} style={{ marginTop: 8 }}><span className="badge">{link.evidence.type}</span><p className="muted">{link.evidence.content.slice(0, 1200)}</p></div>)}</details></article>)}</section></> : null}</div></main>;
}
